FROM {{ namespace }}/neutron-base:{{ tag }}
MAINTAINER {{ maintainer }}

RUN apt-get -y install --no-install-recommends \
        net-tools \
    && apt-get clean

RUN curl -o calico-{{ calico_version }}.tar.gz https://codeload.github.com/projectcalico/calico/tar.gz/{{ calico_version }} \
    && tar -zxvf calico-{{ calico_version }}.tar.gz

# TODO: (adidenko) Replace hardcode hacking with configurable prefix when it's supported
RUN sed -e 's#FELIX_PREFIX = "felix-"#FELIX_PREFIX = "ccp-"#' -i /calico-{{ calico_version }}/calico/felix/frules.py
RUN sed -e 's#FELIX_PFX = "felix-"#FELIX_PFX = "ccp-"#' -i /calico-{{ calico_version }}/calico/felix/ipsets.py

RUN cd /calico-{{ calico_version }} \
    && /var/lib/microservices/venv/bin/pip --no-cache-dir install --upgrade /calico-{{ calico_version }}

ENV PATH /var/lib/microservices/venv/bin:$PATH
