upgrade:
  name: upgrade-neutron
  image: neutron-base
  steps:
    - name: backup
      command: /tmp/backup.sh
      files:
        - backup-sh
      volumes:
        - name: backup-dir
          path: /var/ccp/backup/neutron
          type: host
          readOnly: false
      topology_key: backup
    - name: expand
      command: neutron-db-manage upgrade --expand
      files:
        - neutron.conf
    - name: kill-server
      type: kill-services
      services: [neutron-server]
    - name: contract
      command: neutron-db-manage upgrade --contract
      files:
        - neutron.conf
    - name: roll-server
      type: rolling-upgrade
      services: [neutron-server]
    - name: roll-l2
      type: rolling-upgrade
      services: [neutron-openvswitch-agent]
    - name: roll-agents
      type: rolling-upgrade
      services:
        - neutron-l3-agent
        - neutron-dhcp-agent
        - neutron-metadata-agent
files:
  neutron.conf:
    path: /etc/neutron/neutron.conf
    content: neutron.conf.j2
    perm: "0600"
  backup-sh:
    path: /tmp/backup.sh
    content: backup.sh.j2
    perm: "500"
