FROM {{ image_spec("base-tools") }}
MAINTAINER {{ maintainer }}

RUN apt-get update && apt-get -y install --no-install-recommends \
{% if ovs_version == "system" %}
        openvswitch-switch \
{% else %}
        gcc \
        libc6-dev \
        libssl-dev \
        libcap-ng-dev \
        make \
        module-init-tools \
        xz-utils && \
{% if dpdk_version != "none" %}
    curl -LO {{ url.dpdk }}/dpdk-{{ dpdk_version }}.tar.xz && \
    tar -xf dpdk-{{ dpdk_version }}.tar.xz && \
    rm -f dpdk-{{ dpdk_version }}.tar.xz && \
    rename "s/-stable//" dpdk-* && \
    cd dpdk-{{ dpdk_version }} && \
    sed -i "/UIO\\|KMOD\\|KNI\\|POWER/s/=.*/=n/" config/common_linuxapp && \
    make install T=x86_64-native-linuxapp-gcc DESTDIR=install && \
    cd tools && \
    install dpdk-devbind.py dpdk-pmdinfo.py /usr/bin && \
    cd ../.. && \
{% endif %}
    curl -LO {{ url.ovs }}/openvswitch-{{ ovs_version }}.tar.gz && \
    tar -xf openvswitch-{{ ovs_version }}.tar.gz && \
    rm -f openvswitch-{{ ovs_version }}.tar.gz && \
    cd openvswitch-{{ ovs_version }} && \
    ./configure \
{% if dpdk_version != "none" %}
        --with-dpdk=../dpdk-{{ dpdk_version }}/x86_64-native-linuxapp-gcc \
{% endif %}
        --prefix=/usr \
        --localstatedir=/var \
        --sysconfdir=/etc && \
    make && make install && make clean && \
    cd .. && \
{% if dpdk_version != "none" %}
    rm -rf dpdk-{{ dpdk_version }} && \
{% endif %}
    rm -rf openvswitch-{{ ovs_version }} && \
    apt-get purge -y \
      gcc \
      libc6-dev \
      libssl-dev \
      libcap-ng-dev \
      make \
      module-init-tools \
      xz-utils && \
    apt-get autoremove && \
{% endif %}
    apt-get clean
